### PR TITLE
virtio: use 2k22 virtio drivers

### PR DESCRIPTION
**Pull request by ym**
Add support for 2k22 virtio drivers.

Build versions are from https://www.techthoughts.info/windows-version-numbers/

### CODE REVIEW

**Comment by ader1990** [comment]
Hello and thank you for the PR. Last time we checked, the 2k22 virtio drivers were the same binaries as the 2k19 ones. Is there a change with the newer drivers?

**Comment by nullptr0000** [comment]
Having tripped over this, the 2K22 drivers are *currently* still the same binaries so the only real consequence is the messages reporting the 2K19 drivers being installed.  This does make the very dangerous assumption that the 2K19 and 2K22 drivers will always be identical.

*However* as & when support for 2K25 is added, the drivers binaries for 2K25 *ARE* different so it makes sense to properly extend the VirtIODriverMappings table to allow for proper future compatibility.

**Comment by ader1990** [comment]
> Having tripped over this, the 2K22 drivers are _currently_ still the same binaries so the only real consequence is the messages reporting the 2K19 drivers being installed. This does make the very dangerous assumption that the 2K19 and 2K22 drivers will always be identical.
> 
> _However_ as & when support for 2K25 is added, the drivers binaries for 2K25 _ARE_ different so it makes sense to properly extend the VirtIODriverMappings table to allow for proper future compatibility.

@nullptr0000 agreed, this PR should be merged. According to https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info, 2025 should be around 26100 version.

**Comment by ader1990** [comment]
For future reference:

```
Get-FileHash -Algorithm MD5 F:\vioscsi\2k22\amd64\vioscsi.sys

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             A1E5D8D91ACEB072F534DCFB9AEE935F                                       F:\vioscsi\2k22\amd64\vioscsi.sys


Get-FileHash -Algorithm MD5 F:\vioscsi\2k19\amd64\vioscsi.sys

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             A1E5D8D91ACEB072F534DCFB9AEE935F                                       F:\vioscsi\2k19\amd64\vioscsi.sys


Get-FileHash -Algorithm MD5 F:\vioscsi\2k25\amd64\vioscsi.sys

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             D3C74E10FA5BCC215257BE19534AF03F                                       F:\vioscsi\2k25\amd64\vioscsi.sys
```

**Pull request merged**
